version: "3"
services:
    db-server:
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        container_name: db-server
        ports: 
            - "1433:1433"
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "Super123Password"
            