version: '3'

services:
  api:
    build: .
    ports:
      - "5200:80"
    depends_on:
      - db
    environment:
      - MONGO_ADDRESS=db:27017
      - ASPNETCORE_ENVIRONMENT=Development
  db:
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"
